### ISSUE TITLE
Little syntax improvements

### ISSUE THREAD

**Issue by sampsyo** [cucapra/hbir#11]
In the `data` section:

- [ ] The `local` vs. `global` declaration is redundant. (The destination memory covers that.) We can remove it.
- [ ] Instead of `host` and `device`, use `<-` and `->`. And `=` for scratch buffers.
- [ ] Eliminate the `block` attribute. (`block` vs. `stripe` goes right into the declaration.)

**Comment by sampsyo** [comment]
These are taken care of in the new data declarations. The input/output distinction is indicated with `in` and `out` keywords, like this:
https://github.com/cucapra/hbir/blob/bf6baf3d2908940c3c6de86f603f27a5f2d7cbae/lotus/tests/vvadd.hbir#L17-L20
