### ISSUE TITLE
Feature wish list

### ISSUE THREAD

**Issue by sampsyo** [cucapra/hbir#4]
Some longer-term ideas for language improvements:

- [ ] The `config` section should be a more complete abstraction over the `target`. Specifically, `data` and `code` should never refer to `target` constructs directly—they should _always_ be intermediated by names given in `config`.
- [ ] Accelerators.
    - [ ] Basic support for declaring fixed accelerators (and their interfaces) in `target`. And support for invoking them in `code`.
    - [ ] Similar declarations for _configured_ spatial accelerators in `config`.
    - [ ] Asynchronous accelerator invocation: `async` to start the accelerator, then `await` to block and wait for its results.
- [ ] Constructs in the `code` section for message passing between threads (simple `send` and `receive` constructs). This would facilitate a more spatial programming model, as opposed to the current focus on SPMD.
- [ ] A binary format for the language (suitable for generation from frontends).
- [ ] Symbolic targets. This is the key to portability: express the _range_ of possible machines that an HBIR program can target.

More medium-sized extensions:

- [ ] Dynamic memory allocation (and dynamically-sized `data` buffers).

(Edit this issue text to add more!)
